#!/bin/sh

cmake \
	-DCMAKE_CXX_COMPILER=g++ \
	-DCMAKE_C_COMPILER=gcc \
	-DCMAKE_Fortran_COMPILER=gfortran \
	-DCMAKE_INSTALL_PREFIX:PATH=$HOME/opt/fexception \
	-DPY_SYSCONFIG_SCHEME=posix_user \
	-DPYTHON_EXECUTABLE=`which python` \
	-DTHREAD_SAFE=YES \
	$@
